[package]
name = "ed25519_proofs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2_ed25519 = {git = "https://github.com/zkSocial-zklisbon/plonky2-ed25519.git", branch = "main"}
